"""Verificar cambios en modelo Oferta

Revision ID: 0b2baf643691
Revises: 4c89ef90edaf
Create Date: 2025-09-23 11:08:55.462149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2baf643691'
down_revision = '4c89ef90edaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Oferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_oferta', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('whatsapplink', sa.Text(), nullable=True))
        batch_op.drop_column('nombre_cs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Oferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_cs', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('whatsapplink')
        batch_op.drop_column('nombre_oferta')

    # ### end Alembic commands ###
