"""add inscripcion promocion asistencia premios metodo_pago pago

Revision ID: 1a571d03515e
Revises: 59bbca4f4daa
Create Date: 2025-11-06 14:09:31.981301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a571d03515e'
down_revision = '59bbca4f4daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Metodo_pago',
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_metodo_pago')
    )
    op.create_table('Promocion',
    sa.Column('id_promocion', sa.BigInteger(), nullable=False),
    sa.Column('Oferta_id_oferta', sa.BigInteger(), nullable=False),
    sa.Column('nombre_promocion', sa.String(length=50), nullable=False),
    sa.Column('descricpcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('publico_objetivo', sa.String(length=20), nullable=False),
    sa.Column('porcentaje_descuento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('paquetes_especificos', sa.String(length=50), nullable=False),
    sa.Column('aplica_nuevos_usuarios', sa.Boolean(), nullable=True),
    sa.Column('tiene_sorteo', sa.Boolean(), nullable=False),
    sa.Column('cantidad_premios', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Oferta_id_oferta'], ['Oferta.id_oferta'], ),
    sa.PrimaryKeyConstraint('id_promocion')
    )
    op.create_table('Inscripcion',
    sa.Column('id_inscripcion', sa.BigInteger(), nullable=False),
    sa.Column('Persona_id_persona', sa.BigInteger(), nullable=False),
    sa.Column('Paquete_id_paquete', sa.BigInteger(), nullable=False),
    sa.Column('Promocion_id_promocion', sa.BigInteger(), nullable=True),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('precio_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('clases_usadas', sa.Integer(), nullable=False),
    sa.Column('clases_restantes', sa.Integer(), nullable=True),
    sa.Column('pago_a_cuotas', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Paquete_id_paquete'], ['Paquete.id_paquete'], ),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.ForeignKeyConstraint(['Promocion_id_promocion'], ['Promocion.id_promocion'], ),
    sa.PrimaryKeyConstraint('id_inscripcion')
    )
    op.create_table('Premios',
    sa.Column('id_premio', sa.Integer(), nullable=False),
    sa.Column('Promocion_id_promocion', sa.BigInteger(), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Promocion_id_promocion'], ['Promocion.id_promocion'], ),
    sa.PrimaryKeyConstraint('id_premio')
    )
    op.create_table('Asistencia',
    sa.Column('id_asistencia', sa.BigInteger(), nullable=False),
    sa.Column('Inscripcion_id_inscripcion', sa.BigInteger(), nullable=False),
    sa.Column('Horario_sesion_id_horario_sesion', sa.BigInteger(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Horario_sesion_id_horario_sesion'], ['HorarioSesion.id_horario_sesion'], ),
    sa.ForeignKeyConstraint(['Inscripcion_id_inscripcion'], ['Inscripcion.id_inscripcion'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_table('Pago',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('Inscripcion_id_inscripcion', sa.BigInteger(), nullable=False),
    sa.Column('Metodo_pago_id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_confirmacion_director', sa.DateTime(), nullable=True),
    sa.Column('confirmado_por', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Inscripcion_id_inscripcion'], ['Inscripcion.id_inscripcion'], ),
    sa.ForeignKeyConstraint(['Metodo_pago_id_metodo_pago'], ['Metodo_pago.id_metodo_pago'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pago')
    op.drop_table('Asistencia')
    op.drop_table('Premios')
    op.drop_table('Inscripcion')
    op.drop_table('Promocion')
    op.drop_table('Metodo_pago')
    # ### end Alembic commands ###
