"""add capacidad_maxima and cupos_ocupados to horario_sesion

Revision ID: 2b3c4d5e6f7g
Revises: 1a571d03515e
Create Date: 2025-11-07 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3c4d5e6f7g'
down_revision = '1a571d03515e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad_maxima', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cupos_ocupados', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.drop_column('cupos_ocupados')
        batch_op.drop_column('capacidad_maxima')

    # ### end Alembic commands ###