"""fix asistencia nullable fields

Revision ID: 3c4d5e6f7g8h
Revises: 2b3c4d5e6f7g
Create Date: 2025-11-07 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4d5e6f7g8h'
down_revision = '2b3c4d5e6f7g'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Asistencia', schema=None) as batch_op:
        batch_op.alter_column('asistio',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Asistencia', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('asistio',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###