"""actualizar_persona_campos_nullable

Revision ID: 59bbca4f4daa
Revises: 1413959ce722
Create Date: 2025-10-27 03:18:38.162288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bbca4f4daa'
down_revision = '1413959ce722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_cuenta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('temporal', sa.Boolean(), nullable=True))
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('celular',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Persona', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('celular',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('temporal')
        batch_op.drop_column('tipo_cuenta')

    # ### end Alembic commands ###
