"""change_fecha_pago_to_date

Revision ID: ae67f9ae1df2
Revises: eeb64f3b8796
Create Date: 2025-12-01 00:26:33.272089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae67f9ae1df2'
down_revision = 'eeb64f3b8796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pago', schema=None) as batch_op:
        batch_op.alter_column('fecha_pago',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pago', schema=None) as batch_op:
        batch_op.alter_column('fecha_pago',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
