"""Actualizar Horario (dias, hora_inicio, hora_fin) y HorarioSesion (motivo nullable)

Revision ID: af8c0182fa54
Revises: 6b9a67ce3e61
Create Date: 2025-10-14 12:19:38.029168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8c0182fa54'
down_revision = '6b9a67ce3e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Horario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activo_desde', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('activo_hasta', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_recurrente', sa.Boolean(), nullable=False))
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.drop_column('motivo')
        batch_op.drop_column('cancelado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('motivo', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('es_recurrente')

    with op.batch_alter_table('Horario', schema=None) as batch_op:
        batch_op.drop_column('precio')
        batch_op.drop_column('activo_hasta')
        batch_op.drop_column('activo_desde')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
