"""Agregar columna Premios_id_premio a tabla Ganador

Revision ID: beea975f62eb
Revises: e507b7c2ea12
Create Date: 2025-12-09 12:20:38.403370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beea975f62eb'
down_revision = 'e507b7c2ea12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ganador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Premios_id_premio', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Premios', ['Premios_id_premio'], ['id_premio'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ganador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Premios_id_premio')

    # ### end Alembic commands ###
