"""Add numero_cuotas and montos_cuotas to Inscripcion

Revision ID: c84018049f11
Revises: 00a7051fc847
Create Date: 2025-11-28 12:21:23.680136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84018049f11'
down_revision = '00a7051fc847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Promocion', schema=None) as batch_op:
        batch_op.drop_column('premios_descuentos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Promocion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premios_descuentos', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
