"""Change Alumno.zona from String to Text

Revision ID: ccea68093325
Revises: de2097d52398
Create Date: 2025-12-08 19:11:11.695957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccea68093325'
down_revision = 'de2097d52398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zona', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alumno', schema=None) as batch_op:
        batch_op.drop_column('zona')

    # ### end Alembic commands ###
