"""Add payment_intent_id to Pago table

Revision ID: e507b7c2ea12
Revises: ccea68093325
Create Date: 2025-12-09 04:52:57.378079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e507b7c2ea12'
down_revision = 'ccea68093325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['payment_intent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
