"""agregar tablas notificacion y notificacion_persona

Revision ID: f84fe732fc1f
Revises: 3c4d5e6f7g8h
Create Date: 2025-11-13 16:06:08.571566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84fe732fc1f'
down_revision = '3c4d5e6f7g8h'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('notificacion_persona',
    sa.Column('id_notificacion_persona', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Notificacion_id_notificacion', sa.BigInteger(), nullable=False),
    sa.Column('Persona_id_persona', sa.BigInteger(), nullable=False),
    sa.Column('Inscricpcion_id_inscricpcion', sa.BigInteger(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_leida', sa.DateTime(), nullable=True),
    sa.Column('enviada_sistema', sa.Boolean(), nullable=True),
    sa.Column('enviada_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('enviada_push', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio_push', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio_whatsapp', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Inscricpcion_id_inscricpcion'], ['Inscripcion.id_inscripcion'], ),
    sa.ForeignKeyConstraint(['Notificacion_id_notificacion'], ['notificacion.id_notificacion'], ),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_notificacion_persona')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacion_persona')
    op.drop_table('notificacion')
    # ### end Alembic commands ###
