"""Cambiar mensaje de notificacion de VARCHAR a TEXT

Revision ID: 057fba218259
Revises: ba0c486dd3dd
Create Date: 2025-11-16 20:40:22.460907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '057fba218259'
down_revision = 'ba0c486dd3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Permiso', schema=None) as batch_op:
        batch_op.alter_column('permiso_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID único del permiso',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('persona_id_persona',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID de la persona que solicita el permiso',
               existing_nullable=False)
        batch_op.alter_column('inscripcion_id_inscripcion',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID de la inscripción relacionada',
               existing_nullable=False)
        batch_op.alter_column('asistencia_original_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID de la asistencia original que se quiere cambiar',
               existing_nullable=False)
        batch_op.alter_column('motivo',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Motivo por el cual se solicita el cambio',
               existing_nullable=False)
        batch_op.alter_column('horario_sesion_id_horario_sesion',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID del horario sesión de reemplazo deseado',
               existing_nullable=False)
        batch_op.alter_column('fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha y hora de la solicitud',
               existing_nullable=False)
        batch_op.alter_column('estado_permiso',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Estado del permiso: PENDIENTE, APROBADO, RECHAZADO',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'::character varying"))
        batch_op.alter_column('motivo_rechazo',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Motivo del rechazo si aplica',
               existing_nullable=True)
        batch_op.alter_column('fecha_respuesta',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha y hora de la respuesta',
               existing_nullable=True)
        batch_op.alter_column('respondida_por',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID de la persona que respondió (director/admin)',
               existing_nullable=True)
        batch_op.alter_column('asistencia_reemplazo_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='ID de la nueva asistencia de reemplazo si fue aprobada',
               existing_nullable=True)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si el permiso está activo o fue eliminado lógicamente',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_table_comment(
        existing_comment='Tabla para gestionar solicitudes de cambio de clases por parte de los alumnos (renombrada para consistencia)'
    )

    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=600),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('Permiso', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tabla para gestionar solicitudes de cambio de clases por parte de los alumnos (renombrada para consistencia)',
        existing_comment=None
    )
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               comment='Si el permiso está activo o fue eliminado lógicamente',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('asistencia_reemplazo_id',
               existing_type=sa.BIGINT(),
               comment='ID de la nueva asistencia de reemplazo si fue aprobada',
               existing_nullable=True)
        batch_op.alter_column('respondida_por',
               existing_type=sa.BIGINT(),
               comment='ID de la persona que respondió (director/admin)',
               existing_nullable=True)
        batch_op.alter_column('fecha_respuesta',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha y hora de la respuesta',
               existing_nullable=True)
        batch_op.alter_column('motivo_rechazo',
               existing_type=sa.TEXT(),
               comment='Motivo del rechazo si aplica',
               existing_nullable=True)
        batch_op.alter_column('estado_permiso',
               existing_type=sa.VARCHAR(length=30),
               comment='Estado del permiso: PENDIENTE, APROBADO, RECHAZADO',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'::character varying"))
        batch_op.alter_column('fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha y hora de la solicitud',
               existing_nullable=False)
        batch_op.alter_column('horario_sesion_id_horario_sesion',
               existing_type=sa.BIGINT(),
               comment='ID del horario sesión de reemplazo deseado',
               existing_nullable=False)
        batch_op.alter_column('motivo',
               existing_type=sa.TEXT(),
               comment='Motivo por el cual se solicita el cambio',
               existing_nullable=False)
        batch_op.alter_column('asistencia_original_id',
               existing_type=sa.BIGINT(),
               comment='ID de la asistencia original que se quiere cambiar',
               existing_nullable=False)
        batch_op.alter_column('inscripcion_id_inscripcion',
               existing_type=sa.BIGINT(),
               comment='ID de la inscripción relacionada',
               existing_nullable=False)
        batch_op.alter_column('persona_id_persona',
               existing_type=sa.BIGINT(),
               comment='ID de la persona que solicita el permiso',
               existing_nullable=False)
        batch_op.alter_column('permiso_id',
               existing_type=sa.BIGINT(),
               comment='ID único del permiso',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
