"""iniciar migraciones

Revision ID: 0d357d52e65a
Revises: 
Create Date: 2025-09-22 12:42:59.974658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d357d52e65a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estilo',
    sa.Column('id_estilo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_estilo', sa.String(length=100), nullable=False),
    sa.Column('descripcion_estilo', sa.Text(), nullable=True),
    sa.Column('beneficios_estilo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_estilo')
    )
    op.create_table('Paquete',
    sa.Column('id_paquete', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cantidad_clases', sa.Integer(), nullable=False),
    sa.Column('dias_validez', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_paquete')
    )
    op.create_table('Persona',
    sa.Column('id_persona', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('celular', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('solicitud_user_especial', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('Programa',
    sa.Column('id_programa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.String(length=100), nullable=False),
    sa.Column('descricpcion_programa', sa.Text(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_programa')
    )
    op.create_table('Sala',
    sa.Column('id_sala', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_sala', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.Text(), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('zona', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('ciclo',
    sa.Column('id_ciclo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_ciclo')
    )
    op.create_table('Alumno',
    sa.Column('id_alumno', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Persona_id_persona', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_alumno')
    )
    op.create_table('Categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Programa_id_programa', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion_categoria', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Programa_id_programa'], ['Programa.id_programa'], ),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('Director',
    sa.Column('id_director', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Persona_id_persona', sa.Integer(), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_director')
    )
    op.create_table('Profesor',
    sa.Column('id_profesor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Persona_id_persona', sa.Integer(), nullable=False),
    sa.Column('frase', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('redes_sociales', sa.Text(), nullable=True),
    sa.Column('cuidad', sa.String(length=50), nullable=True),
    sa.Column('experiencia', sa.Integer(), nullable=True),
    sa.Column('signo', sa.String(length=20), nullable=True),
    sa.Column('musica', sa.String(length=200), nullable=True),
    sa.Column('estilos', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_profesor')
    )
    op.create_table('Subcategoria',
    sa.Column('id_subcategoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Categoria_id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_subcategoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion_subcategoria', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Categoria_id_categoria'], ['Categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_subcategoria')
    )
    op.create_table('Oferta',
    sa.Column('id_oferta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ciclo_id_ciclo', sa.Integer(), nullable=False),
    sa.Column('Subcategoria_id_subcategoria', sa.Integer(), nullable=False),
    sa.Column('nombre_cs', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('visibilidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Subcategoria_id_subcategoria'], ['Subcategoria.id_subcategoria'], ),
    sa.ForeignKeyConstraint(['ciclo_id_ciclo'], ['ciclo.id_ciclo'], ),
    sa.PrimaryKeyConstraint('id_oferta')
    )
    op.create_table('Horario',
    sa.Column('id_horario', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Oferta_id_oferta', sa.Integer(), nullable=False),
    sa.Column('Estilo_id_estilo', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.Integer(), nullable=False),
    sa.Column('Profesor_id_profesor', sa.Integer(), nullable=False),
    sa.Column('Sala_id_sala', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('duracion', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Estilo_id_estilo'], ['Estilo.id_estilo'], ),
    sa.ForeignKeyConstraint(['Oferta_id_oferta'], ['Oferta.id_oferta'], ),
    sa.ForeignKeyConstraint(['Profesor_id_profesor'], ['Profesor.id_profesor'], ),
    sa.ForeignKeyConstraint(['Sala_id_sala'], ['Sala.id_sala'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('Paquete_oferta',
    sa.Column('id_paquete_oferta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Oferta_id_oferta', sa.Integer(), nullable=False),
    sa.Column('Paquete_id_paquete', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Oferta_id_oferta'], ['Oferta.id_oferta'], ),
    sa.ForeignKeyConstraint(['Paquete_id_paquete'], ['Paquete.id_paquete'], ),
    sa.PrimaryKeyConstraint('id_paquete_oferta')
    )
    op.create_table('Sesion',
    sa.Column('id_sesion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Horario_id_horario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Horario_id_horario'], ['Horario.id_horario'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sesion')
    op.drop_table('Paquete_oferta')
    op.drop_table('Horario')
    op.drop_table('Oferta')
    op.drop_table('Subcategoria')
    op.drop_table('Profesor')
    op.drop_table('Director')
    op.drop_table('Categoria')
    op.drop_table('Alumno')
    op.drop_table('ciclo')
    op.drop_table('Sala')
    op.drop_table('Programa')
    op.drop_table('Persona')
    op.drop_table('Paquete')
    op.drop_table('Estilo')
    # ### end Alembic commands ###
