"""Eliminar Paquete_Oferta y modificar Paquete con FK a Oferta

Revision ID: 1413959ce722
Revises: 8c0626daa8e6
Create Date: 2025-10-23 15:15:31.586662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1413959ce722'
down_revision = '8c0626daa8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Paquete_Oferta')
    with op.batch_alter_table('Paquete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Oferta_id_oferta', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('id_paquete',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('cantidad_clases',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'Oferta', ['Oferta_id_oferta'], ['id_oferta'])
        batch_op.drop_column('precio_sugerido')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Paquete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('precio_sugerido', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cantidad_clases',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_paquete',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('precio')
        batch_op.drop_column('Oferta_id_oferta')

    op.create_table('Paquete_Oferta',
    sa.Column('id_paquete_oferta', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('Paquete_id_paquete', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Oferta_id_oferta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Oferta_id_oferta'], ['Oferta.id_oferta'], name=op.f('Paquete_Oferta_Oferta_id_oferta_fkey')),
    sa.ForeignKeyConstraint(['Paquete_id_paquete'], ['Paquete.id_paquete'], name=op.f('Paquete_Oferta_Paquete_id_paquete_fkey')),
    sa.PrimaryKeyConstraint('id_paquete_oferta', name=op.f('Paquete_Oferta_pkey'))
    )
    # ### end Alembic commands ###
