"""aumentar_tamaño_motivo_horario_sesion_a_1000_caracteres

Revision ID: 3a3b370c31d3
Revises: 057fba218259
Create Date: 2025-11-17 06:34:21.655831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3b370c31d3'
down_revision = '057fba218259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)

    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
