"""Agregar link_ubicacion a Sala

Revision ID: 4c89ef90edaf
Revises: efd867493027
Create Date: 2025-09-23 08:36:29.985506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c89ef90edaf'
down_revision = 'efd867493027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_ubicacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Sala', schema=None) as batch_op:
        batch_op.drop_column('link_ubicacion')

    # ### end Alembic commands ###
