"""Add Elenco and AlumnoFemme models

Revision ID: 50c3812a4232
Revises: 0d357d52e65a
Create Date: 2025-09-22 14:26:02.094859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c3812a4232'
down_revision = '0d357d52e65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alumno_Femme',
    sa.Column('id_alumno_femme', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Persona_id_persona', sa.BigInteger(), nullable=False),
    sa.Column('cumpleanos', sa.Date(), nullable=False),
    sa.Column('signo', sa.String(length=30), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_alumno_femme')
    )
    op.create_table('Elenco',
    sa.Column('id_elenco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Persona_id_persona', sa.BigInteger(), nullable=False),
    sa.Column('departamento', sa.String(length=20), nullable=True),
    sa.Column('cumpleanos', sa.Date(), nullable=True),
    sa.Column('signo', sa.String(length=30), nullable=False),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Persona_id_persona'], ['Persona.id_persona'], ),
    sa.PrimaryKeyConstraint('id_elenco')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Elenco')
    op.drop_table('Alumno_Femme')
    # ### end Alembic commands ###
