"""Agregar fecha, motivo y cancelado a HorarioSesion

Revision ID: 6b9a67ce3e61
Revises: 73fd7cb8986e
Create Date: 2025-10-14 11:11:23.993914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9a67ce3e61'
down_revision = '73fd7cb8986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.drop_column('es_recurrente')
        batch_op.add_column(sa.Column('motivo', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('cancelado', sa.Boolean(), nullable=False, server_default='false'))
    
    # Convertir fecha de VARCHAR a DATE usando USING
    op.execute('ALTER TABLE "HorarioSesion" ALTER COLUMN fecha TYPE DATE USING fecha::DATE')
    op.alter_column('HorarioSesion', 'fecha', nullable=False, existing_type=sa.Date())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('HorarioSesion', 'fecha', type_=sa.String(length=10), existing_type=sa.Date(), nullable=True)
    
    with op.batch_alter_table('HorarioSesion', schema=None) as batch_op:
        batch_op.drop_column('cancelado')
        batch_op.drop_column('motivo')
        batch_op.add_column(sa.Column('es_recurrente', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###
