"""Crear tabla HorarioSesion

Revision ID: 73fd7cb8986e
Revises: a4776fd53d01
Create Date: 2025-10-14 09:37:17.938168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fd7cb8986e'
down_revision = 'a4776fd53d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HorarioSesion',
    sa.Column('id_horario_sesion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Horario_id_horario', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('duracion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=True),
    sa.Column('es_recurrente', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Horario_id_horario'], ['Horario.id_horario'], ),
    sa.PrimaryKeyConstraint('id_horario_sesion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HorarioSesion')
    # ### end Alembic commands ###
