"""Aplicar cambios manuales de modelos: paquete_oferta y horario_sesion

Revision ID: a4776fd53d01
Revises: 0b2baf643691
Create Date: 2025-10-10 17:35:09.343870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4776fd53d01'
down_revision = '0b2baf643691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Paquete_Oferta',
    sa.Column('id_paquete_oferta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Paquete_id_paquete', sa.Integer(), nullable=False),
    sa.Column('Oferta_id_oferta', sa.BigInteger(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Oferta_id_oferta'], ['Oferta.id_oferta'], ),
    sa.ForeignKeyConstraint(['Paquete_id_paquete'], ['Paquete.id_paquete'], ),
    sa.PrimaryKeyConstraint('id_paquete_oferta')
    )
    op.drop_table('Paquete_oferta')
    with op.batch_alter_table('Horario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activo_desde', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('activo_hasta', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('dia')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('modalidad')
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('duracion')

    with op.batch_alter_table('Oferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_cursos', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('publico_objetivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('repite_semanalmente', sa.Boolean(), nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('visibilidad')

    with op.batch_alter_table('Paquete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('precio_sugerido', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ilimitado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Paquete', schema=None) as batch_op:
        batch_op.drop_column('ilimitado')
        batch_op.drop_column('precio_sugerido')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('Oferta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibilidad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('repite_semanalmente')
        batch_op.drop_column('publico_objetivo')
        batch_op.drop_column('cantidad_cursos')

    with op.batch_alter_table('Horario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracion', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hora_fin', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('modalidad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dia', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('precio')
        batch_op.drop_column('activo_hasta')
        batch_op.drop_column('activo_desde')
        batch_op.drop_column('tipo')

    op.create_table('Paquete_oferta',
    sa.Column('id_paquete_oferta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Oferta_id_oferta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Paquete_id_paquete', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Oferta_id_oferta'], ['Oferta.id_oferta'], name=op.f('Paquete_oferta_Oferta_id_oferta_fkey')),
    sa.ForeignKeyConstraint(['Paquete_id_paquete'], ['Paquete.id_paquete'], name=op.f('Paquete_oferta_Paquete_id_paquete_fkey')),
    sa.PrimaryKeyConstraint('id_paquete_oferta', name=op.f('Paquete_oferta_pkey'))
    )
    op.drop_table('Paquete_Oferta')
    # ### end Alembic commands ###
